CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    invite_code VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_phone UNIQUE (phone),
    CONSTRAINT uk_app_user_invite_code UNIQUE (invite_code),
    CONSTRAINT ck_app_user_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_app_user_balance CHECK (balance >= 0),
    CONSTRAINT ck_app_user_code_by_role CHECK (
        (role = 'USER' AND invite_code IS NOT NULL) OR
        (role = 'ADMIN' AND invite_code IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS affiliate_relation (
    invitee_user_id BIGINT NOT NULL PRIMARY KEY,
    inviter_user_id BIGINT NOT NULL,
    invite_code_snapshot VARCHAR(32) NOT NULL,
    bound_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_relation_invitee FOREIGN KEY (invitee_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_relation_inviter FOREIGN KEY (inviter_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_relation_not_self CHECK (invitee_user_id <> inviter_user_id)
);

CREATE TABLE IF NOT EXISTS recharge_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    out_trade_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    rebate_amount DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    balance_after DECIMAL(19, 2) NOT NULL,
    paid_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_recharge_trade_no UNIQUE (out_trade_no),
    CONSTRAINT uk_recharge_request UNIQUE (user_id, request_key),
    CONSTRAINT fk_recharge_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_recharge_amount CHECK (amount > 0),
    CONSTRAINT ck_recharge_rebate CHECK (rebate_amount >= 0),
    CONSTRAINT ck_recharge_balance CHECK (balance_after >= 0)
);

CREATE TABLE IF NOT EXISTS affiliate_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_order_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_ledger_source_order UNIQUE (source_order_id),
    CONSTRAINT fk_ledger_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_ledger_order FOREIGN KEY (source_order_id) REFERENCES recharge_order (id),
    CONSTRAINT ck_ledger_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_relation_inviter_bound ON affiliate_relation (inviter_user_id, bound_at);
CREATE INDEX IF NOT EXISTS idx_recharge_user_created ON recharge_order (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ledger_user_created ON affiliate_ledger (user_id, created_at);
